---
- name: "Install InSpec if available via package manager (best-effort)"
  shell: |
    if command -v inspec >/dev/null; then exit 0; fi
    if command -v dnf >/dev/null; then sudo dnf -y install inspec || true; fi
    if command -v apt >/dev/null; then sudo apt -y install inspec || true; fi
  changed_when: false
  failed_when: false

- name: "Download linux-baseline profile"
  get_url:
    url: "{{ inspec_profile_url }}"
    dest: "{{ report_dir }}/linux-baseline.tar.gz"
    mode: "0640"

- name: "Run InSpec profile (best-effort)"
  shell: "inspec exec {{ report_dir }}/linux-baseline.tar.gz --reporter json:{{ report_dir }}/inspec_linux_baseline.json || true"
  changed_when: false
  failed_when: false
